spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  session:
    jdbc:
      initialize-schema: always

logging.level:
  org.hibernate.SQL: debug

# swagger-ui path
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs/json